language: cpp
os: linux
dist: bionic

env:
  global:
    # Global build options and C++ flags
    - CMAKE_OPTIONS="-DCMAKE_EXPORT_COMPILE_COMMANDS=ON"
    - CXX_FLAGS="-Wall -pedantic -Werror"

jobs:
  include:
    - compiler: gcc
      addons:
        apt:
          update: true
          packages:
            - gcc
            - g++
            - clang
            - clang-format
            - clang-tidy
    - compiler: clang
      addons:
        apt:
          update: true
          packages:
            - clang
            - clang-format
            - clang-tidy

before_install:
  # Combine global build options with OS/compiler-dependent options
  - export CMAKE_OPTIONS=${CMAKE_OPTIONS}" "${ENV_CMAKE_OPTIONS}
  - export CXX_FLAGS=${CXX_FLAGS}" "${ENV_CXX_FLAGS}

install:
  - echo ${PATH}
  - echo ${CXX}
  - ${CXX} --version
  - ${CXX} -v

script:
  ########################
  # Build main and tests #
  ########################
  - mkdir -p build && cd build
  - cmake ${CMAKE_OPTIONS} -DCMAKE_CXX_FLAGS=${CXX_FLAGS} ..
  - cmake --build . -- -j$(($(nproc)-1))
  - cmake --build . --target check-format
  - cmake --build . --target check-tidy
