cmake_minimum_required(VERSION 3.3)

macro(enable_clang_tidy)
    find_program(clang_tidy_cmd NAMES "clang-tidy")
    if(NOT clang_tidy_cmd)
        message(WARNING "clang-tidy not found!")
    else()
        if(NOT EXISTS "${CMAKE_SOURCE_DIR}/.clang-tidy")
            message(FATAL_ERROR "'${CMAKE_SOURCE_DIR}/.clang-tidy' not found!")
        endif()
        set(CMAKE_CXX_CLANG_TIDY "${clang_tidy_cmd};-use-color;-quiet")
        message(STATUS "Enabled clang-tidy: ${clang_tidy_cmd}")
    endif()
endmacro()
